export const RESOURCE_TYPES = {
  PRODUCT: "PRODUCT",
  COLLECTION: "COLLECTION",
  ARTICLE: "ARTICLE",
  BLOG: "BLOG",
  PAGE: "PAGE",
  SHOP: "SHOP",
};

export const RESOURCE_TYPE_ARRAY = Array.from(Object.values(RESOURCE_TYPES));

export const LATER = {
  ARTICLE: "ARTICLE",
  ARTICLE_IMAGE: "ARTICLE_IMAGE",
  BLOG: "BLOG",
  COLLECTION: "COLLECTION",
  COLLECTION_IMAGE: "COLLECTION_IMAGE",
  DELIVERY_METHOD_DEFINITION: "DELIVERY_METHOD_DEFINITION",
  EMAIL_TEMPLATE: "EMAIL_TEMPLATE",
  FILTER: "FILTER",
  LINK: "LINK",
  MEDIA_IMAGE: "MEDIA_IMAGE",
  MENU: "MENU",
  METAFIELD: "METAFIELD",
  METAOBJECT: "METAOBJECT",
  ONLINE_STORE_THEME: "ONLINE_STORE_THEME",
  ONLINE_STORE_THEME_APP_EMBED: "ONLINE_STORE_THEME_APP_EMBED",
  ONLINE_STORE_THEME_JSON_TEMPLATE: "ONLINE_STORE_THEME_JSON_TEMPLATE",
  ONLINE_STORE_THEME_LOCALE_CONTENT: "ONLINE_STORE_THEME_LOCALE_CONTENT",
  ONLINE_STORE_THEME_SECTION_GROUP: "ONLINE_STORE_THEME_SECTION_GROUP",
  ONLINE_STORE_THEME_SETTINGS_CATEGORY: "ONLINE_STORE_THEME_SETTINGS_CATEGORY",
  ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS:
    "ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS",
  PACKING_SLIP_TEMPLATE: "PACKING_SLIP_TEMPLATE",
  PAGE: "PAGE",
  PAYMENT_GATEWAY: "PAYMENT_GATEWAY",
  PRODUCT: "PRODUCT",
  PRODUCT_OPTION: "PRODUCT_OPTION",
  PRODUCT_OPTION_VALUE: "PRODUCT_OPTION_VALUE",
  SELLING_PLAN: "SELLING_PLAN",
  SELLING_PLAN_GROUP: "SELLING_PLAN_GROUP",
  SHOP: "SHOP",
  SHOP_POLICY: "SHOP_POLICY",
};
